services:
  traefik:
    image: traefik:v2.9
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=quickdrawpjt@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"

  fastapi:
    image: quickdraw/backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`quick-draw-pjt.com`) && (PathPrefix(`/api/v1`) || PathPrefix(`/ws/`))"
      - "traefik.http.routers.fastapi.entrypoints=websecure"
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"

  react:
    image: quickdraw/frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`quick-draw-pjt.com`)"
      - "traefik.http.routers.react.entrypoints=websecure"
      - "traefik.http.routers.react.tls.certresolver=myresolver"
