version: "3.8"

services:
  nginx:
    image: hyomin2677/quickdraw-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api-gateway
      - websocket-gateway
    restart: always

  api-gateway:
    image: hyomin2677/quickdraw-api-gateway
    restart: always

  websocket-gateway:
    image: hyomin2677/quickdraw-websocket-gateway
    restart: always

  user-service:
    image: hyomin2677/quickdraw-user-service
    restart: always

  room-service:
    image: hyomin2677/quickdraw-room-service
    restart: always

  draw-service:
    image: hyomin2677/quickdraw-draw-service
    restart: always

  redis:
    image: redis
    restart: always
