version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:6.2"
    container_name: redis_server
    ports:
      - "6379:6379"
