name: deploy
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 ubuntu@${{ secrets.SERVER_PUBLIC_IP }} << EOF
          cd /home/ubuntu/QuickDraw/
          docker-compose stop fastapi react
          docker-compose rm -f fastapi react
          docker image prune -a -f   
          docker-compose up -d    
          EOF

          rm /tmp/ssh_key
