name: room-service
on:
  push:
    branches:
      - room-service

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} > fastapi/room-service/.env
          echo BASE_URL=${{ secrets.BASE_URL }} >> fastapi/room-service/.env
          echo API_GATEWAY_URL=${{ secrets.API_GATEWAY_URL }} >> fastapi/room-service/.env
          echo ROOM_DB_URL=${{ secrets.DB_URL }}/room >> fastapi/room-service/.env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> fastapi/room-service/.env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd fastapi/room-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/quickdraw-room-service .
          docker push ${{ secrets.DOCKER_USERNAME }}/quickdraw-room-service

      - name: Deploy
        run: |
          set -eux
          echo "${{secrets.SSH_PRIVATE_KEY}}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 ubuntu@${{ secrets.SERVER_PUBLIC_IP }} << EOF
          set -eux
          cd /home/ubuntu/
          docker-compose stop room-service
          docker-compose rm -f room-service
          docker-compose pull room-service
          docker-compose up -d room-service
          EOF

          rm /tmp/ssh_key
