name: user-service
on:
  push:
    branches:
      - user-service

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} > fastapi/user-service/.env
          echo BASE_URL=${{ secrets.BASE_URL }} >> fastapi/user-service/.env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> fastapi/user-service/.env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> fastapi/user-service/.env
          echo USER_DB_URL=${{ secrets.DB_URL }}/user >> fastapi/user-service/.env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> fastapi/user-service/.env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd fastapi/user-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/quickdraw-user-service .
          docker push ${{ secrets.DOCKER_USERNAME }}/quickdraw-user-service

      - name: Deploy
        run: |
          set -eux
          echo "${{secrets.SSH_PRIVATE_KEY}}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 ubuntu@${{ secrets.SERVER_PUBLIC_IP }} << EOF
          set -eux
          cd /home/ubuntu/
          docker-compose stop user-service
          docker-compose rm -f user-service
          docker image prune -af
          docker-compose pull user-service
          docker-compose up -d user-service
          EOF

          rm /tmp/ssh_key
