name: websocket-gateway
on:
  push:
    branches:
      - websocket-gateway

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo BASE_URL=${{ secrets.BASE_URL }} > fastapi/websocket-gateway/.env
          echo DRAW_SERVICE_URL=${{ secrets.DRAW_SERVICE_URL }} >> fastapi/websocket-gateway/.env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd fastapi/api-gateway
          docker build -t ${{ secrets.DOCKER_USERNAME }}/quickdraw-websocket-gateway .
          docker push ${{ secrets.DOCKER_USERNAME }}/quickdraw-websocket-gateway

      - name: Deploy
        run: |
          set -eux
          echo "${{secrets.SSH_PRIVATE_KEY}}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 ubuntu@${{ secrets.SERVER_PUBLIC_IP }} << EOF
          set -eux
          cd /home/ubuntu/
          docker-compose stop websocket-gateway
          docker-compose rm -f websocket-gateway
          docker image prune -af
          docker-compose pull websocket-gateway
          docker-compose up -d websocket-gateway
          EOF

          rm /tmp/ssh_key
